### ISSUE TITLE
Any examples of other payment processors?

### ISSUE THREAD

**Issue by erral** [4teamwork/ftw.shop#39]
Hi:

Do you have any example of an external payment-processor?

I need an external payment processor for my project, and I think that I will need something more than the actual implementation for the external processor checks.

Now, it checks if it's external and directly redirects there. I may need some pre-processing and post-processing. I will try to work on that and then create a pull-request if you have nothing done.

Danke,

Mikel

**Comment by lukasgraf** [comment]
Hey Mikel,

currently we only have one implementation of an external payment processor, and that code is not in a public GitHub repo yet.

However, here's the gist of it:
https://gist.github.com/lukasgraf/834d3f257f8be2ab1aaf 

As you can see, we do some checking for preconditions in the `available()` method of the processor, but that's about it for this implementation.

If you can come up with something that suits your use-case and offers a way to do pre/post processing  in a way generic enough to be included in `ftw.shop` I'll be happy to have a look at it!

**Comment by erral** [comment]
Thanks, I think that I can manage to do what I need with your example.
